name: Provision Server

on:
  workflow_dispatch

jobs:
  create-deployment-artifacts:
    name: Create deployment artifacts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Create server provision artifact
        env:
          GITHUB_SHA: ${{ github.sha }}
        run: tar -czf nixos-"${GITHUB_SHA}".tar.gz nixos/*
      - name: Store artifact for distribution
        uses: actions/upload-artifact@v4
        with:
          name: server-build
          path: nixos-${{ github.sha }}.tar.gz

  prepare-provision-on-server:
    name: Prepare Provision
    runs-on: ubuntu-latest
    needs: create-deployment-artifacts
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: server-build

      - name: Upload
        uses: burnett01/rsync-deployments@6.0.0
        with:
          switches: --mkpath
          path: nixos-${{github.sha}}.tar.gz
          remote_path: ${{ vars.HOST_PATH }}/artifacts
          remote_host: ${{ vars.HOST_IP }}
          remote_user: ${{ secrets.HOST_USER }}
          remote_key: ${{ secrets.HOST_KEY }}

  provision:
    name: Provision Server
    runs-on: ubuntu-latest
    needs: [ create-deployment-artifacts, prepare-provision-on-server ]
    steps:
      - name: Provision server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ vars.HOST_IP }}
          username: ${{ secrets.HOST_USER }}
          key: ${{ secrets.HOST_KEY }}
          script: |
            mkdir -p ${{ vars.HOST_PATH }}/storage/{app,public,framework,logs}
            mkdir -p ${{ vars.HOST_PATH }}/storage/framework/{cache,sessions,testing,views}
            echo "${{ secrets.HOST_PASS }}" | sudo -S chmod -R 0777 ${{ vars.HOST_PATH }}/storage
            cd ${{ vars.HOST_PATH }}/artifacts
            sed -i 's/HOSTUSER/${{ secrets.HOST_USER }}/g' configuration.nix
            echo "${{ secrets.HOST_PASS }}" | sudo -S mv configuration.nix /etc/nixos/configuration.nix
            echo "${{ secrets.HOST_PASS }}" | sudo -S nixos-rebuild switch

